name: lint

on:
  push:
    branches:
      - '**'

jobs:
  Shell_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shellcheck Version Check
        run: shellcheck -V

      - name: Run ShellCheck
        run: shellcheck *.sh

